### ISSUE TITLE
Fix the CI and update deps

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/flake8-broken-line#133]
Currently, there are errors in our CI: https://travis-ci.com/github/sobolevn/flake8-broken-line/jobs/334338507

It needs to be fixed. Probably it would be safe to say that `poetry update` will do the thing. 
And it is also required to update lots of deps from @dependabot-bot updates that are not mergable at the moment.
List: https://github.com/sobolevn/flake8-broken-line/pulls

**Comment by ydanilin** [comment]
Hello!
I can fix this issue.
Did I understand correct, that I should do the following steps:
- Fork https://github.com/sobolevn/flake8-broken-line
- Clone the fork and set upstream ```git remote add upstream``` to the original
- Understand the project and do failed command ```poetry run safety check --bare --full-report``` from Travis log
- Fix failed command locally and submit pull request from my fork to original

Is it the way to go (sorry for noob questions)?

**Comment by sobolevn** [comment]
Yes, correct! Thanks a lot for your help! 👍

**Comment by ydanilin** [comment]
> And it is also required to update lots of deps from @dependabot-bot updates that are not mergable 
at the moment.
List: https://github.com/sobolevn/flake8-broken-line/pulls

So for some reasons these automatic (?) pull requests cannot be processed further, yes?
Do they need to be updated "manually" the same way I did with #133?
If yes, I will do that.

**Comment by sobolevn** [comment]
Yes, manual update will be the easiest way.
