### ISSUE TITLE
Typo: "Found backslash that is used for line breaking"

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/flake8-broken-line#14]
Not "braking". Thanks to https://www.reddit.com/r/Python/comments/aldo62/flake8brokenline_flake8_plugin_to_forbid_in_your/effvbh2/

**Comment by peterjc** [comment]
Fixed in f5de297923fa4249b3d4774c0f08b53a77f2cd92 but not yet in a release on PyPI

**Comment by sobolevn** [comment]
Thanks! I don't want to release a documentation only change.
I will wait for the feature / bugfix to release something meaningful.
